### ISSUE TITLE
More supported formats, please

### ISSUE THREAD

**Issue by Ryan19930926** [Saertox/bunkr-downloader#2]
Currently, no formats other than MP4 will be downloaded. Being able to add MOV, MKV, etc. might be better.

**Comment by Saertox** [comment]
Please use this now: https://github.com/Jules-WinnfieldX/CyberDropDownloader

this project was just a quick thing when bunkr downloads werent working in the cyberdrop downloader, it never was supposed to mean anything.

now that the cyberdrop downloader developer fixed bunkr downloads, i strongly recommend using his project
